config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root :to => 'messages#index'

  resources :messages do
    member do
      patch :mark_as_read
    end
    collection do
      post :lost_prescription
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inbox.rb
class Inbox < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  # Associations
  belongs_to :outbox
  belongs_to :inbox

  # Constants
  PATIENT_LOST_PRESCREPTION = "I've lost my script, please issue a new one at a charge of €10."
  
  # Callbacks
  after_create :increment_inbox_unread_count
  after_update :decrement_inbox_unread_count

  # Class methods
  def self.latest(user_id)
    Message.joins(inbox: :user).where(user: { id: user_id }).last
  end

  # Instance methods
  def is_in_past_week?
    created_at > Time.now - 1.week
  end

  def increment_inbox_unread_count
    self.inbox.update(unread_count: self.inbox.unread_count + 1)
  end

  def decrement_inbox_unread_count
    if saved_change_to_read? && self.read
      self.inbox.update(unread_count: self.inbox.unread_count - 1)
    end
  end

  def debit_payment_from_patient(user)
    if self.body === PATIENT_LOST_PRESCREPTION
      PaymentProviderFactory.provider.debit_card(user)
      Payment.create(user_id: user.id)
    end
  rescue => e
    # Logger can be addded
    p "Error occoured while calling payment provider"
  end
end

app/models/outbox.rb
class Outbox < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :messages
end

app/models/payment.rb
class Payment < ApplicationRecord
  # Associations
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Associations
  has_one :inbox
  has_one :outbox
  has_many :payments
  has_many :messages

  # Scopes 
  scope :patient, -> { where(is_patient: true) }
  scope :admin, -> { where(is_admin: true) }
  scope :doctor, -> { where(is_doctor: true) }

  # Class methods
  def self.current
    User.patient.first
  end

  def self.default_admin
    User.admin.first
  end

  def self.default_doctor
    User.doctor.first
  end

  # Instance methods
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def create
    current_user = User.current
    params_hash = message_params.merge(outbox_id: current_user.outbox.id)

    if User.current.is_patient
      if Message.latest(current_user.id).is_in_past_week?
        params_hash.merge!(inbox_id: User.doctor.first.inbox.id)
      else
        params_hash.merge!(inbox_id: User.admin.first.inbox.id)
      end
    else
      params_hash.merge!(inbox_id: User.patient.first.inbox.id)
    end

    @message = Message.new(params_hash)
    if @message.valid?
      @message.save!
      redirect_to '/messages'
    else
      # More errors can be handled
      redirect_to '/422.html'
    end
  end

  def lost_prescription
    current_user = User.current
    @message = Message.new(
      body: Message::PATIENT_LOST_PRESCREPTION,
      outbox_id: current_user.outbox.id,
      inbox_id: User.admin.first.inbox.id
    )

    if @message.save!
      @message.debit_payment_from_patient(current_user)
      redirect_to '/messages'
    else
      # More errors can be handled
      redirect_to '/422.html'
    end
  end

  def mark_as_read
    @message = Message.find(params[:id])
    @message.update(read: true)

    redirect_to '/'
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NuaMessaging</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-light">
    <%= render 'navigation/header' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/index.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0">Inbox <strong>(<%= User.current.inbox.unread_count %>)</strong></h6>
  <% User.current.inbox.messages.each do |message| %>
    <%= link_to message do %>
      <div class="media text-muted pt-3">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><%= message.outbox.user.first_name %> <%= message.outbox.user.last_name %></strong>
          <%= message.body.truncate(45) %>
        </p>
      </div>
    <% end %>
  <% end %>

  <small class="d-block text-right mt-3">
    <a href="#">All updates</a>
  </small>
</div>

app/views/messages/new.html.erb
<div class="card mt-3">
  <h5 class="card-header">
    New Message
  </h5>

  <div class="card-body">
    <%= form_for @message do |f| %>
      <div class="form-group py-3">
        <%= f.text_area :body, class: "form-control", rows: 3 %>
      </div>

      <div class="form-group mb-0 text-right">
        <%= f.submit 'Send Message', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

</div>

app/views/messages/show.html.erb
<div class="card my-3 ">
  <h5 class="card-header">
    <% if @message.outbox.user.is_doctor? %>Dr.<% end %>
    <%= @message.outbox.user.full_name %>
  </h5>
  <div class="card-body">
    <p class="card-text"><%= @message.body %></p>
    <%= link_to "Reply", new_message_path, class: "btn btn-primary" %>
    <%= link_to "I've lost my prescription", lost_prescription_messages_path, data: { "turbo-method": :post }, class: "btn btn-primary" %>
    <% if !@message.read %>
      <%= link_to "Mark as read", mark_as_read_message_path(id: @message.id), data: { "turbo-method": :patch }, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/navigation/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Nua Messaging</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to messages_path, class: 'nav-link' do %>
          Inbox
        <% end  %>
      </li>
    </ul>
  </div>
</nav>